#include "ASRuntimeBind_30Module.h"
#include "AngelscriptBinds.h"
#include "Quartz/AudioMixerClockHandle.h"
void FASRuntimeBind_30Module::Bind_QuartzClockHandle()
{
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "GetBeatProgressPercent", { ERASE_METHOD_PTR(UQuartzClockHandle, GetBeatProgressPercent, (EQuartzCommandQuantization,  float,  float), ERASE_ARGUMENT_PACK( float )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "GetBeatsPerMinute", { ERASE_METHOD_PTR(UQuartzClockHandle, GetBeatsPerMinute, (const UObject*) const, ERASE_ARGUMENT_PACK( float )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "GetCurrentTimestamp", { ERASE_METHOD_PTR(UQuartzClockHandle, GetCurrentTimestamp, (const UObject*), ERASE_ARGUMENT_PACK( FQuartzTransportTimeStamp )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "GetDurationOfQuantizationTypeInSeconds", { ERASE_METHOD_PTR(UQuartzClockHandle, GetDurationOfQuantizationTypeInSeconds, (const UObject*,  const EQuartzCommandQuantization&,  float), ERASE_ARGUMENT_PACK( float )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "GetEstimatedRunTime", { ERASE_METHOD_PTR(UQuartzClockHandle, GetEstimatedRunTime, (const UObject*), ERASE_ARGUMENT_PACK( float )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "GetMillisecondsPerTick", { ERASE_METHOD_PTR(UQuartzClockHandle, GetMillisecondsPerTick, (const UObject*) const, ERASE_ARGUMENT_PACK( float )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "GetSecondsPerTick", { ERASE_METHOD_PTR(UQuartzClockHandle, GetSecondsPerTick, (const UObject*) const, ERASE_ARGUMENT_PACK( float )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "GetThirtySecondNotesPerMinute", { ERASE_METHOD_PTR(UQuartzClockHandle, GetThirtySecondNotesPerMinute, (const UObject*) const, ERASE_ARGUMENT_PACK( float )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "GetTicksPerSecond", { ERASE_METHOD_PTR(UQuartzClockHandle, GetTicksPerSecond, (const UObject*) const, ERASE_ARGUMENT_PACK( float )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "IsClockRunning", { ERASE_METHOD_PTR(UQuartzClockHandle, IsClockRunning, (const UObject*), ERASE_ARGUMENT_PACK( bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "NotifyOnQuantizationBoundary", { ERASE_METHOD_PTR(UQuartzClockHandle, NotifyOnQuantizationBoundary, (const UObject*,  FQuartzQuantizationBoundary,  const FOnQuartzCommandEventBP&,  float), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "PauseClock", { ERASE_METHOD_PTR(UQuartzClockHandle, PauseClock, (const UObject*,  UQuartzClockHandle*&), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "ResetTransport", { ERASE_METHOD_PTR(UQuartzClockHandle, ResetTransport, (const UObject*,  const FOnQuartzCommandEventBP&), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "ResetTransportQuantized", { ERASE_METHOD_PTR(UQuartzClockHandle, ResetTransportQuantized, (const UObject*,  FQuartzQuantizationBoundary,  const FOnQuartzCommandEventBP&,  UQuartzClockHandle*&), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "ResumeClock", { ERASE_METHOD_PTR(UQuartzClockHandle, ResumeClock, (const UObject*,  UQuartzClockHandle*&), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "SetBeatsPerMinute", { ERASE_METHOD_PTR(UQuartzClockHandle, SetBeatsPerMinute, (const UObject*,  const FQuartzQuantizationBoundary&,  const FOnQuartzCommandEventBP&,  UQuartzClockHandle*&,  float), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "SetMillisecondsPerTick", { ERASE_METHOD_PTR(UQuartzClockHandle, SetMillisecondsPerTick, (const UObject*,  const FQuartzQuantizationBoundary&,  const FOnQuartzCommandEventBP&,  UQuartzClockHandle*&,  float), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "SetSecondsPerTick", { ERASE_METHOD_PTR(UQuartzClockHandle, SetSecondsPerTick, (const UObject*,  const FQuartzQuantizationBoundary&,  const FOnQuartzCommandEventBP&,  UQuartzClockHandle*&,  float), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "SetThirtySecondNotesPerMinute", { ERASE_METHOD_PTR(UQuartzClockHandle, SetThirtySecondNotesPerMinute, (const UObject*,  const FQuartzQuantizationBoundary&,  const FOnQuartzCommandEventBP&,  UQuartzClockHandle*&,  float), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "SetTicksPerSecond", { ERASE_METHOD_PTR(UQuartzClockHandle, SetTicksPerSecond, (const UObject*,  const FQuartzQuantizationBoundary&,  const FOnQuartzCommandEventBP&,  UQuartzClockHandle*&,  float), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "StartClock", { ERASE_METHOD_PTR(UQuartzClockHandle, StartClock, (const UObject*,  UQuartzClockHandle*&), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "StartOtherClock", { ERASE_METHOD_PTR(UQuartzClockHandle, StartOtherClock, (const UObject*,  FName,  FQuartzQuantizationBoundary,  const FOnQuartzCommandEventBP&), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "StopClock", { ERASE_METHOD_PTR(UQuartzClockHandle, StopClock, (const UObject*,  bool,  UQuartzClockHandle*&), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "SubscribeToAllQuantizationEvents", { ERASE_METHOD_PTR(UQuartzClockHandle, SubscribeToAllQuantizationEvents, (const UObject*,  const FOnQuartzMetronomeEventBP&,  UQuartzClockHandle*&), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "SubscribeToQuantizationEvent", { ERASE_METHOD_PTR(UQuartzClockHandle, SubscribeToQuantizationEvent, (const UObject*,  EQuartzCommandQuantization,  const FOnQuartzMetronomeEventBP&,  UQuartzClockHandle*&), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "UnsubscribeFromAllTimeDivisions", { ERASE_METHOD_PTR(UQuartzClockHandle, UnsubscribeFromAllTimeDivisions, (const UObject*,  UQuartzClockHandle*&), ERASE_ARGUMENT_PACK( void )) } );
			FAngelscriptBinds::AddFunctionEntry(UQuartzClockHandle::StaticClass(), "UnsubscribeFromTimeDivision", { ERASE_METHOD_PTR(UQuartzClockHandle, UnsubscribeFromTimeDivision, (const UObject*,  EQuartzCommandQuantization,  UQuartzClockHandle*&), ERASE_ARGUMENT_PACK( void )) } );
}
