#include "ASRuntimeBind_60Module.h"
#include "AngelscriptBinds.h"
#include "InterchangeAnimSequenceFactoryNode.h"
void FASRuntimeBind_60Module::Bind_InterchangeAnimSequenceFactoryNode()
{
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetAnimatedAttributeCurveName", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetAnimatedAttributeCurveName, (const int32,  FString&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetAnimatedAttributeCurveNames", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetAnimatedAttributeCurveNames, (TArray<FString>&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetAnimatedAttributeCurveNamesCount", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetAnimatedAttributeCurveNamesCount, () const, ERASE_ARGUMENT_PACK(int32 )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetAnimatedAttributeStepCurveName", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetAnimatedAttributeStepCurveName, (const int32,  FString&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetAnimatedAttributeStepCurveNames", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetAnimatedAttributeStepCurveNames, (TArray<FString>&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetAnimatedAttributeStepCurveNamesCount", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetAnimatedAttributeStepCurveNamesCount, () const, ERASE_ARGUMENT_PACK(int32 )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetAnimatedMaterialCurveSuffixe", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetAnimatedMaterialCurveSuffixe, (const int32,  FString&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetAnimatedMaterialCurveSuffixes", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetAnimatedMaterialCurveSuffixes, (TArray<FString>&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetAnimatedMaterialCurveSuffixesCount", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetAnimatedMaterialCurveSuffixesCount, () const, ERASE_ARGUMENT_PACK(int32 )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomAddCurveMetadataToSkeleton", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomAddCurveMetadataToSkeleton, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomDeleteExistingCustomAttributeCurves", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomDeleteExistingCustomAttributeCurves, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomDeleteExistingMorphTargetCurves", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomDeleteExistingMorphTargetCurves, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomDeleteExistingNonCurveCustomAttributes", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomDeleteExistingNonCurveCustomAttributes, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomDoNotImportCurveWithZero", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomDoNotImportCurveWithZero, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomImportAttributeCurves", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomImportAttributeCurves, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomImportBoneTracks", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomImportBoneTracks, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomImportBoneTracksRangeStart", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomImportBoneTracksRangeStart, (double&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomImportBoneTracksRangeStop", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomImportBoneTracksRangeStop, (double&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomImportBoneTracksSampleRate", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomImportBoneTracksSampleRate, (double&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomMaterialDriveParameterOnCustomAttribute", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomMaterialDriveParameterOnCustomAttribute, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomRemoveCurveRedundantKeys", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomRemoveCurveRedundantKeys, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomSkeletonFactoryNodeUid", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomSkeletonFactoryNodeUid, (FString&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetCustomSkeletonSoftObjectPath", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetCustomSkeletonSoftObjectPath, (FSoftObjectPath&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetMorphTargetNodeAnimationPayloadKeys", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetMorphTargetNodeAnimationPayloadKeys, (TMap<FString, FInterchangeAnimationPayLoadKey>&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetObjectClass", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetObjectClass, () const, ERASE_ARGUMENT_PACK( class UClass* )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "GetSceneNodeAnimationPayloadKeys", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, GetSceneNodeAnimationPayloadKeys, (TMap<FString, FInterchangeAnimationPayLoadKey>&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "InitializeAnimSequenceNode", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, InitializeAnimSequenceNode, (const FString&,  const FString&), ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "RemoveAnimatedAttributeCurveName", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, RemoveAnimatedAttributeCurveName, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "RemoveAnimatedAttributeStepCurveName", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, RemoveAnimatedAttributeStepCurveName, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "RemoveAnimatedMaterialCurveSuffixe", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, RemoveAnimatedMaterialCurveSuffixe, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetAnimatedAttributeCurveName", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetAnimatedAttributeCurveName, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetAnimatedAttributeStepCurveName", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetAnimatedAttributeStepCurveName, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetAnimatedMaterialCurveSuffixe", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetAnimatedMaterialCurveSuffixe, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetAnimationPayloadKeysForMorphTargetNodeUids", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetAnimationPayloadKeysForMorphTargetNodeUids, (const TMap<FString, FString>&,  const TMap<FString, uint8>&), ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetAnimationPayloadKeysForSceneNodeUids", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetAnimationPayloadKeysForSceneNodeUids, (const TMap<FString, FString>&,  const TMap<FString, uint8>&), ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomAddCurveMetadataToSkeleton", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomAddCurveMetadataToSkeleton, (const bool&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomDeleteExistingCustomAttributeCurves", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomDeleteExistingCustomAttributeCurves, (const bool&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomDeleteExistingMorphTargetCurves", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomDeleteExistingMorphTargetCurves, (const bool&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomDeleteExistingNonCurveCustomAttributes", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomDeleteExistingNonCurveCustomAttributes, (const bool&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomDoNotImportCurveWithZero", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomDoNotImportCurveWithZero, (const bool&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomImportAttributeCurves", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomImportAttributeCurves, (const bool&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomImportBoneTracks", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomImportBoneTracks, (const bool&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomImportBoneTracksRangeStart", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomImportBoneTracksRangeStart, (const double&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomImportBoneTracksRangeStop", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomImportBoneTracksRangeStop, (const double&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomImportBoneTracksSampleRate", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomImportBoneTracksSampleRate, (const double&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomMaterialDriveParameterOnCustomAttribute", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomMaterialDriveParameterOnCustomAttribute, (const bool&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomRemoveCurveRedundantKeys", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomRemoveCurveRedundantKeys, (const bool&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomSkeletonFactoryNodeUid", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomSkeletonFactoryNodeUid, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeAnimSequenceFactoryNode::StaticClass(), "SetCustomSkeletonSoftObjectPath", { ERASE_METHOD_PTR(UInterchangeAnimSequenceFactoryNode, SetCustomSkeletonSoftObjectPath, (const FSoftObjectPath&), ERASE_ARGUMENT_PACK(bool )) } );
}
