#include "ASRuntimeBind_40Module.h"
#include "AngelscriptBinds.h"
//#include "InterchangeAnimationTrackSetNode.h"
//void FASRuntimeBind_40Module::Bind_InterchangeSkeletalAnimationTrackNode()
//{
			//FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalAnimationTrackNode::StaticClass(), "GetCustomAnimationSampleRate", { ERASE_METHOD_PTR(UInterchangeSkeletalAnimationTrackNode, GetCustomAnimationSampleRate, (double&) const, ERASE_ARGUMENT_PACK(bool )) } );
			//FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalAnimationTrackNode::StaticClass(), "GetCustomAnimationStartTime", { ERASE_METHOD_PTR(UInterchangeSkeletalAnimationTrackNode, GetCustomAnimationStartTime, (double&) const, ERASE_ARGUMENT_PACK(bool )) } );
			//FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalAnimationTrackNode::StaticClass(), "GetCustomAnimationStopTime", { ERASE_METHOD_PTR(UInterchangeSkeletalAnimationTrackNode, GetCustomAnimationStopTime, (double&) const, ERASE_ARGUMENT_PACK(bool )) } );
			//FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalAnimationTrackNode::StaticClass(), "GetCustomSkeletonNodeUid", { ERASE_METHOD_PTR(UInterchangeSkeletalAnimationTrackNode, GetCustomSkeletonNodeUid, (FString&) const, ERASE_ARGUMENT_PACK(bool )) } );
			//FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalAnimationTrackNode::StaticClass(), "GetMorphTargetNodeAnimationPayloadKeys", { ERASE_METHOD_PTR(UInterchangeSkeletalAnimationTrackNode, GetMorphTargetNodeAnimationPayloadKeys, (TMap<FString, FString>&,  TMap<FString, uint8>&) const, ERASE_ARGUMENT_PACK(void )) } );
			//FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalAnimationTrackNode::StaticClass(), "GetSceneNodeAnimationPayloadKeys", { ERASE_METHOD_PTR(UInterchangeSkeletalAnimationTrackNode, GetSceneNodeAnimationPayloadKeys, (TMap<FString, FString>&,  TMap<FString, uint8>&) const, ERASE_ARGUMENT_PACK(void )) } );
			//FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalAnimationTrackNode::StaticClass(), "SetAnimationPayloadKeyForMorphTargetNodeUid", { ERASE_METHOD_PTR(UInterchangeSkeletalAnimationTrackNode, SetAnimationPayloadKeyForMorphTargetNodeUid, (const FString&,  const FString&,  const EInterchangeAnimationPayLoadType&), ERASE_ARGUMENT_PACK(bool )) } );
			//FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalAnimationTrackNode::StaticClass(), "SetAnimationPayloadKeyForSceneNodeUid", { ERASE_METHOD_PTR(UInterchangeSkeletalAnimationTrackNode, SetAnimationPayloadKeyForSceneNodeUid, (const FString&,  const FString&,  const EInterchangeAnimationPayLoadType&), ERASE_ARGUMENT_PACK(bool )) } );
			//FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalAnimationTrackNode::StaticClass(), "SetCustomAnimationSampleRate", { ERASE_METHOD_PTR(UInterchangeSkeletalAnimationTrackNode, SetCustomAnimationSampleRate, (const double&), ERASE_ARGUMENT_PACK(bool )) } );
			//FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalAnimationTrackNode::StaticClass(), "SetCustomAnimationStartTime", { ERASE_METHOD_PTR(UInterchangeSkeletalAnimationTrackNode, SetCustomAnimationStartTime, (const double&), ERASE_ARGUMENT_PACK(bool )) } );
			//FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalAnimationTrackNode::StaticClass(), "SetCustomAnimationStopTime", { ERASE_METHOD_PTR(UInterchangeSkeletalAnimationTrackNode, SetCustomAnimationStopTime, (const double&), ERASE_ARGUMENT_PACK(bool )) } );
			//FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalAnimationTrackNode::StaticClass(), "SetCustomSkeletonNodeUid", { ERASE_METHOD_PTR(UInterchangeSkeletalAnimationTrackNode, SetCustomSkeletonNodeUid, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
//}
