#include "ASRuntimeBind_80Module.h"
#include "AngelscriptBinds.h"
#include "InterchangeSkeletalMeshFactoryNode.h"
#include "UObject/NoExportTypes.h"
void FASRuntimeBind_80Module::Bind_InterchangeSkeletalMeshFactoryNode()
{
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "GetCustomBoneInfluenceLimit", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, GetCustomBoneInfluenceLimit, (int32&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "GetCustomCreatePhysicsAsset", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, GetCustomCreatePhysicsAsset, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "GetCustomImportContentType", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, GetCustomImportContentType, (EInterchangeSkeletalMeshContentType&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "GetCustomImportMorphTarget", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, GetCustomImportMorphTarget, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "GetCustomImportVertexAttributes", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, GetCustomImportVertexAttributes, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "GetCustomMorphThresholdPosition", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, GetCustomMorphThresholdPosition, (float&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "GetCustomPhysicAssetSoftObjectPath", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, GetCustomPhysicAssetSoftObjectPath, (FSoftObjectPath&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "GetCustomSkeletonSoftObjectPath", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, GetCustomSkeletonSoftObjectPath, (FSoftObjectPath&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "GetCustomThresholdPosition", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, GetCustomThresholdPosition, (float&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "GetCustomThresholdTangentNormal", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, GetCustomThresholdTangentNormal, (float&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "GetCustomThresholdUV", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, GetCustomThresholdUV, (float&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "GetCustomUseHighPrecisionSkinWeights", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, GetCustomUseHighPrecisionSkinWeights, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "GetObjectClass", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, GetObjectClass, () const, ERASE_ARGUMENT_PACK( class UClass* )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "InitializeSkeletalMeshNode", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, InitializeSkeletalMeshNode, (const FString&,  const FString&,  const FString&), ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "SetCustomBoneInfluenceLimit", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, SetCustomBoneInfluenceLimit, (const int32&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "SetCustomCreatePhysicsAsset", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, SetCustomCreatePhysicsAsset, (const bool&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "SetCustomImportContentType", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, SetCustomImportContentType, (const EInterchangeSkeletalMeshContentType&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "SetCustomImportMorphTarget", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, SetCustomImportMorphTarget, (const bool&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "SetCustomImportVertexAttributes", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, SetCustomImportVertexAttributes, (const bool&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "SetCustomMorphThresholdPosition", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, SetCustomMorphThresholdPosition, (const float&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "SetCustomPhysicAssetSoftObjectPath", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, SetCustomPhysicAssetSoftObjectPath, (const FSoftObjectPath&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "SetCustomSkeletonSoftObjectPath", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, SetCustomSkeletonSoftObjectPath, (const FSoftObjectPath&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "SetCustomThresholdPosition", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, SetCustomThresholdPosition, (const float&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "SetCustomThresholdTangentNormal", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, SetCustomThresholdTangentNormal, (const float&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "SetCustomThresholdUV", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, SetCustomThresholdUV, (const float&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeSkeletalMeshFactoryNode::StaticClass(), "SetCustomUseHighPrecisionSkinWeights", { ERASE_METHOD_PTR(UInterchangeSkeletalMeshFactoryNode, SetCustomUseHighPrecisionSkinWeights, (const bool&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
}
