#include "ASRuntimeBind_80Module.h"
#include "AngelscriptBinds.h"
#include "InterchangeStaticMeshFactoryNode.h"
#include "UObject/NoExportTypes.h"
void FASRuntimeBind_80Module::Bind_InterchangeStaticMeshFactoryNode()
{
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "AddSocketUid", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, AddSocketUid, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "AddSocketUids", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, AddSocketUids, (const TArray<FString>&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetCustomBuildNanite", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetCustomBuildNanite, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetCustomBuildReversedIndexBuffer", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetCustomBuildReversedIndexBuffer, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetCustomBuildScale3D", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetCustomBuildScale3D, (FVector&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetCustomDistanceFieldReplacementMesh", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetCustomDistanceFieldReplacementMesh, (FSoftObjectPath&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetCustomDistanceFieldResolutionScale", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetCustomDistanceFieldResolutionScale, (float&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetCustomDstLightmapIndex", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetCustomDstLightmapIndex, (int32&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetCustomGenerateDistanceFieldAsIfTwoSided", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetCustomGenerateDistanceFieldAsIfTwoSided, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetCustomGenerateLightmapUVs", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetCustomGenerateLightmapUVs, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetCustomMaxLumenMeshCards", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetCustomMaxLumenMeshCards, (int32&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetCustomMinLightmapResolution", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetCustomMinLightmapResolution, (int32&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetCustomSrcLightmapIndex", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetCustomSrcLightmapIndex, (int32&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetCustomSupportFaceRemap", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetCustomSupportFaceRemap, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetObjectClass", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetObjectClass, () const, ERASE_ARGUMENT_PACK( class UClass* )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetSocketUidCount", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetSocketUidCount, () const, ERASE_ARGUMENT_PACK(int32 )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "GetSocketUids", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, GetSocketUids, (TArray<FString>&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "InitializeStaticMeshNode", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, InitializeStaticMeshNode, (const FString&,  const FString&,  const FString&), ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "RemoveSocketUd", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, RemoveSocketUd, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "SetCustomBuildNanite", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, SetCustomBuildNanite, (const bool&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "SetCustomBuildReversedIndexBuffer", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, SetCustomBuildReversedIndexBuffer, (const bool&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "SetCustomBuildScale3D", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, SetCustomBuildScale3D, (const FVector&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "SetCustomDistanceFieldReplacementMesh", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, SetCustomDistanceFieldReplacementMesh, (const FSoftObjectPath&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "SetCustomDistanceFieldResolutionScale", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, SetCustomDistanceFieldResolutionScale, (const float&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "SetCustomDstLightmapIndex", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, SetCustomDstLightmapIndex, (const int32&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "SetCustomGenerateDistanceFieldAsIfTwoSided", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, SetCustomGenerateDistanceFieldAsIfTwoSided, (const bool&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "SetCustomGenerateLightmapUVs", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, SetCustomGenerateLightmapUVs, (const bool&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "SetCustomMaxLumenMeshCards", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, SetCustomMaxLumenMeshCards, (const int32&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "SetCustomMinLightmapResolution", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, SetCustomMinLightmapResolution, (const int32&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "SetCustomSrcLightmapIndex", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, SetCustomSrcLightmapIndex, (const int32&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshFactoryNode::StaticClass(), "SetCustomSupportFaceRemap", { ERASE_METHOD_PTR(UInterchangeStaticMeshFactoryNode, SetCustomSupportFaceRemap, (const bool&,  bool), ERASE_ARGUMENT_PACK(bool )) } );
}
