#include "ASRuntimeBind_50Module.h"
#include "AngelscriptBinds.h"
#include "InterchangeStaticMeshLodDataNode.h"
void FASRuntimeBind_50Module::Bind_InterchangeStaticMeshLodDataNode()
{
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "AddBoxCollisionMeshUid", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, AddBoxCollisionMeshUid, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "AddCapsuleCollisionMeshUid", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, AddCapsuleCollisionMeshUid, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "AddConvexCollisionMeshUid", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, AddConvexCollisionMeshUid, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "AddMeshUid", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, AddMeshUid, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "AddSphereCollisionMeshUid", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, AddSphereCollisionMeshUid, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "GetBoxCollisionMeshUids", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, GetBoxCollisionMeshUids, (TArray<FString>&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "GetBoxCollisionMeshUidsCount", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, GetBoxCollisionMeshUidsCount, () const, ERASE_ARGUMENT_PACK(int32 )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "GetCapsuleCollisionMeshUids", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, GetCapsuleCollisionMeshUids, (TArray<FString>&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "GetCapsuleCollisionMeshUidsCount", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, GetCapsuleCollisionMeshUidsCount, () const, ERASE_ARGUMENT_PACK(int32 )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "GetConvexCollisionMeshUids", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, GetConvexCollisionMeshUids, (TArray<FString>&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "GetConvexCollisionMeshUidsCount", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, GetConvexCollisionMeshUidsCount, () const, ERASE_ARGUMENT_PACK(int32 )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "GetImportCollision", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, GetImportCollision, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "GetMeshUids", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, GetMeshUids, (TArray<FString>&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "GetMeshUidsCount", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, GetMeshUidsCount, () const, ERASE_ARGUMENT_PACK(int32 )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "GetOneConvexHullPerUCX", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, GetOneConvexHullPerUCX, (bool&) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "GetSphereCollisionMeshUids", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, GetSphereCollisionMeshUids, (TArray<FString>&) const, ERASE_ARGUMENT_PACK(void )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "GetSphereCollisionMeshUidsCount", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, GetSphereCollisionMeshUidsCount, () const, ERASE_ARGUMENT_PACK(int32 )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "RemoveAllBoxCollisionMeshes", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, RemoveAllBoxCollisionMeshes, (), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "RemoveAllCapsuleCollisionMeshes", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, RemoveAllCapsuleCollisionMeshes, (), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "RemoveAllConvexCollisionMeshes", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, RemoveAllConvexCollisionMeshes, (), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "RemoveAllMeshes", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, RemoveAllMeshes, (), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "RemoveAllSphereCollisionMeshes", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, RemoveAllSphereCollisionMeshes, (), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "RemoveBoxCollisionMeshUid", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, RemoveBoxCollisionMeshUid, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "RemoveCapsuleCollisionMeshUid", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, RemoveCapsuleCollisionMeshUid, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "RemoveConvexCollisionMeshUid", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, RemoveConvexCollisionMeshUid, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "RemoveMeshUid", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, RemoveMeshUid, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "RemoveSphereCollisionMeshUid", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, RemoveSphereCollisionMeshUid, (const FString&), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "SetImportCollision", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, SetImportCollision, (bool), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UInterchangeStaticMeshLodDataNode::StaticClass(), "SetOneConvexHullPerUCX", { ERASE_METHOD_PTR(UInterchangeStaticMeshLodDataNode, SetOneConvexHullPerUCX, (bool), ERASE_ARGUMENT_PACK(bool )) } );
}
