#include "ASEditorBind_30Module.h"
#include "AngelscriptBinds.h"
#include "RigEditor/IKRigController.h"
void FASEditorBind_30Module::Bind_IKRigController()
{
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "AddBoneSetting", { ERASE_METHOD_PTR(UIKRigController, AddBoneSetting, (const FName,  int32) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "AddNewGoal", { ERASE_METHOD_PTR(UIKRigController, AddNewGoal, (const FName,  const FName) const, ERASE_ARGUMENT_PACK(FName )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "AddRetargetChain", { ERASE_METHOD_PTR(UIKRigController, AddRetargetChain, (const FName,  const FName,  const FName,  const FName) const, ERASE_ARGUMENT_PACK(FName )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "AddSolver", { ERASE_METHOD_PTR(UIKRigController, AddSolver, (TSubclassOf<UIKRigSolver>) const, ERASE_ARGUMENT_PACK(int32 )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "ApplyAutoFBIK", { ERASE_METHOD_PTR(UIKRigController, ApplyAutoFBIK, (), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "ApplyAutoGeneratedRetargetDefinition", { ERASE_METHOD_PTR(UIKRigController, ApplyAutoGeneratedRetargetDefinition, (), ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "ConnectGoalToSolver", { ERASE_METHOD_PTR(UIKRigController, ConnectGoalToSolver, (const FName,  int32) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "DisconnectGoalFromSolver", { ERASE_METHOD_PTR(UIKRigController, DisconnectGoalFromSolver, (const FName,  int32) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetAllGoals", { ERASE_METHOD_PTR(UIKRigController, GetAllGoals, () const, ERASE_ARGUMENT_PACK(const TArray<UIKRigEffectorGoal*>& )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetBoneExcluded", { ERASE_METHOD_PTR(UIKRigController, GetBoneExcluded, (const FName) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetBoneForGoal", { ERASE_METHOD_PTR(UIKRigController, GetBoneForGoal, (const FName) const, ERASE_ARGUMENT_PACK(FName )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetBoneSettings", { ERASE_METHOD_PTR(UIKRigController, GetBoneSettings, (const FName,  int32) const, ERASE_ARGUMENT_PACK(UObject* )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetEndBone", { ERASE_METHOD_PTR(UIKRigController, GetEndBone, (int32) const, ERASE_ARGUMENT_PACK(FName )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetGoal", { ERASE_METHOD_PTR(UIKRigController, GetGoal, (const FName) const, ERASE_ARGUMENT_PACK(UIKRigEffectorGoal* )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetGoalNameForBone", { ERASE_METHOD_PTR(UIKRigController, GetGoalNameForBone, (const FName) const, ERASE_ARGUMENT_PACK(FName )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetGoalSettingsForSolver", { ERASE_METHOD_PTR(UIKRigController, GetGoalSettingsForSolver, (const FName,  int32) const, ERASE_ARGUMENT_PACK(UObject* )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetIndexOfSolver", { ERASE_METHOD_PTR(UIKRigController, GetIndexOfSolver, (UIKRigSolver*) const, ERASE_ARGUMENT_PACK(int32 )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetNumSolvers", { ERASE_METHOD_PTR(UIKRigController, GetNumSolvers, () const, ERASE_ARGUMENT_PACK(int32 )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetRefPoseTransformOfBone", { ERASE_METHOD_PTR(UIKRigController, GetRefPoseTransformOfBone, (const FName) const, ERASE_ARGUMENT_PACK(FTransform )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetRetargetChainEndBone", { ERASE_METHOD_PTR(UIKRigController, GetRetargetChainEndBone, (const FName) const, ERASE_ARGUMENT_PACK(FName )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetRetargetChainGoal", { ERASE_METHOD_PTR(UIKRigController, GetRetargetChainGoal, (const FName) const, ERASE_ARGUMENT_PACK(FName )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetRetargetChains", { ERASE_METHOD_PTR(UIKRigController, GetRetargetChains, () const, ERASE_ARGUMENT_PACK(const TArray<FBoneChain>& )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetRetargetChainStartBone", { ERASE_METHOD_PTR(UIKRigController, GetRetargetChainStartBone, (const FName) const, ERASE_ARGUMENT_PACK(FName )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetRetargetRoot", { ERASE_METHOD_PTR(UIKRigController, GetRetargetRoot, () const, ERASE_ARGUMENT_PACK(FName )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetRootBone", { ERASE_METHOD_PTR(UIKRigController, GetRootBone, (int32) const, ERASE_ARGUMENT_PACK(FName )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetSkeletalMesh", { ERASE_METHOD_PTR(UIKRigController, GetSkeletalMesh, () const, ERASE_ARGUMENT_PACK(USkeletalMesh* )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetSolverAtIndex", { ERASE_METHOD_PTR(UIKRigController, GetSolverAtIndex, (int32) const, ERASE_ARGUMENT_PACK(UIKRigSolver* )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "GetSolverEnabled", { ERASE_METHOD_PTR(UIKRigController, GetSolverEnabled, (int32) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "IsGoalConnectedToAnySolver", { ERASE_METHOD_PTR(UIKRigController, IsGoalConnectedToAnySolver, (const FName) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "IsGoalConnectedToSolver", { ERASE_METHOD_PTR(UIKRigController, IsGoalConnectedToSolver, (const FName,  int32) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "IsSkeletalMeshCompatible", { ERASE_METHOD_PTR(UIKRigController, IsSkeletalMeshCompatible, (USkeletalMesh*) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "MoveSolverInStack", { ERASE_METHOD_PTR(UIKRigController, MoveSolverInStack, (int32,  int32) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "RemoveBoneSetting", { ERASE_METHOD_PTR(UIKRigController, RemoveBoneSetting, (const FName,  int32) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "RemoveGoal", { ERASE_METHOD_PTR(UIKRigController, RemoveGoal, (const FName) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "RemoveRetargetChain", { ERASE_METHOD_PTR(UIKRigController, RemoveRetargetChain, (const FName) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "RemoveSolver", { ERASE_METHOD_PTR(UIKRigController, RemoveSolver, (const int32) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "RenameGoal", { ERASE_METHOD_PTR(UIKRigController, RenameGoal, (const FName,  const FName) const, ERASE_ARGUMENT_PACK(FName )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "RenameRetargetChain", { ERASE_METHOD_PTR(UIKRigController, RenameRetargetChain, (const FName,  const FName) const, ERASE_ARGUMENT_PACK(FName )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "SetBoneExcluded", { ERASE_METHOD_PTR(UIKRigController, SetBoneExcluded, (const FName,  const bool) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "SetEndBone", { ERASE_METHOD_PTR(UIKRigController, SetEndBone, (const FName,  int32) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "SetGoalBone", { ERASE_METHOD_PTR(UIKRigController, SetGoalBone, (const FName,  const FName) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "SetRetargetChainEndBone", { ERASE_METHOD_PTR(UIKRigController, SetRetargetChainEndBone, (const FName,  const FName) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "SetRetargetChainGoal", { ERASE_METHOD_PTR(UIKRigController, SetRetargetChainGoal, (const FName,  const FName) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "SetRetargetChainStartBone", { ERASE_METHOD_PTR(UIKRigController, SetRetargetChainStartBone, (const FName,  const FName) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "SetRetargetRoot", { ERASE_METHOD_PTR(UIKRigController, SetRetargetRoot, (const FName) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "SetRootBone", { ERASE_METHOD_PTR(UIKRigController, SetRootBone, (const FName,  int32) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "SetSkeletalMesh", { ERASE_METHOD_PTR(UIKRigController, SetSkeletalMesh, (USkeletalMesh*) const, ERASE_ARGUMENT_PACK(bool )) } );
			FAngelscriptBinds::AddFunctionEntry(UIKRigController::StaticClass(), "SetSolverEnabled", { ERASE_METHOD_PTR(UIKRigController, SetSolverEnabled, (int32,  bool) const, ERASE_ARGUMENT_PACK(bool )) } );
}
